ci: tweaks > release.yml
.github/workflows/release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -65,7 +65,7 @@ jobs:
           bunx json -I -f package.json -e "this.version=\"$RELEASE_VERSION\""
           bun install --frozen-lockfile
           bun run build
-          npm publish --provenance --access public --no-git-checks --tag $TAG
+          npm publish --provenance --access public --no-git-checks --tag $TAG || { echo "🔴 Failed to publish package. Exiting."; exit 0; }
 
           PACKAGE_URL="https://www.npmjs.com/package/$PACKAGE_NAME/v/$RELEASE_VERSION"
           if [[ $GITHUB_EVENT_NAME == 'issue_comment' ]]; then
